//************************************************************************************
//**  
//**  File name:     C:\Users\Ucenik\Desktop\stoperica\stoperica.c
//**  Title:         
//**  Description:   
//**  
//**  Generated by:  Flowcode v5.5.2.1
//**  Date:          Wednesday, May 06, 2026 16:15:19
//**  Licence:       Professional
//**  Registered to: xyz
//**  Licence key:   WUK7B9
//**  
//**  
//**  http://www.matrixmultimedia.com
//**  
//************************************************************************************


#define MX_PIC

#define MX_USES_UINT8 1
#define MX_USES_SINT16 0
#define MX_USES_CHAR 0
#define MX_USES_FLOAT 0
#define MX_USES_SINT32 0
#define MX_USES_BOOL 1
#define MX_USES_UINT16 0
#define MX_USES_UINT32 0
//Defines for microcontroller
#define P16F887
#define FC_CAL_PIC
#define MX_ADC
#define MX_ADC_TYPE_7
#define MX_ADC_BITS_10
#define MX_EE
#define MX_EE_TYPE2
#define MX_EE_SIZE 256
#define MX_SPI_1
#define MX_SPI_1_MISO_PORT portc
#define MX_SPI_1_MISO_TRIS trisc
#define MX_SPI_1_MISO_PIN 4
#define MX_SPI_1_MOSI_PORT portc
#define MX_SPI_1_MOSI_TRIS trisc
#define MX_SPI_1_MOSI_PIN 5
#define MX_SPI_1_CLK_PORT portc
#define MX_SPI_1_CLK_TRIS trisc
#define MX_SPI_1_CLK_PIN 3
#define MX_SPI_1_SS_PORT portc
#define MX_SPI_1_SS_TRIS trisc
#define MX_UART_1
#define MX_UART_1_TX_PORT portc
#define MX_UART_1_TX_TRIS trisc
#define MX_UART_1_TX_PIN 6
#define MX_UART_1_RX_PORT portc
#define MX_UART_1_RX_TRIS trisc
#define MX_UART_1_RX_PIN 7
#define MX_I2C
#define MX_MI2C
#define MX_I2C_1
#define MX_I2C_1_SDA_PORT portc
#define MX_I2C_1_SDA_TRIS trisc
#define MX_I2C_1_SDA_PIN 4
#define MX_I2C_1_SCL_PORT portc
#define MX_I2C_1_SCL_TRIS trisc
#define MX_I2C_1_SCL_PIN 3
#define MX_PWM
#define MX_PWM_CNT 2
#define MX_PWM_PSCA1
#define MX_PWM_PSCA4
#define MX_PWM_PSCA16
#define MX_PWM_1_PORT portc
#define MX_PWM_1_TRIS trisc
#define MX_PWM_1_PIN 2
#define MX_PWM_2_PORT portc
#define MX_PWM_2_TRIS trisc
#define MX_PWM_2_PIN 1

//Functions
#define MX_CLK_SPEED 19660800
#ifdef _BOOSTC
#include <system.h>
#endif
#ifdef HI_TECH_C
#include <pic.h>
#endif

//Configuration data
#ifdef _BOOSTC
#pragma DATA 0x2007, 0x23e2
#endif
#ifdef HI_TECH_C
__CONFIG(0x23e2);
#endif
#ifdef _BOOSTC
#pragma DATA 0x2008, 0x3eff
#endif
#ifdef HI_TECH_C
__CONFIG(0x3eff);
#endif

//Internal functions
#include "C:\Program Files (x86)\Flowcode\v5\FCD\internals.c"

//Macro function declarations


//Variable declarations
#define FCV_FALSE (0)
#define FCV_TRUE (1)
MX_UINT8 FCV_MIN1 = (0x0);
MX_UINT8 FCV_PMIN = (0x0);
MX_UINT8 FCV_STOP = (0x0);
MX_UINT8 FCV_RESTART = (0x0);
MX_UINT8 FCV_SEK = (0x0);
MX_UINT8 FCV_STO1;
MX_UINT8 FCV_PSEK = (0x0);
MX_UINT8 FCV_STO = (0x0);
MX_UINT8 FCV_SEK1 = (0x0);
MX_UINT8 FCV_STS = (0x0);
MX_UINT8 FCV_ST1 = (0x0);
MX_UINT8 FCV_MIN = (0x0);
MX_UINT8 FCV_PSTO = (0x0);
MX_UINT8 FCV_ST2 = (0x0);
MX_UINT8 FCV_START = (0x0);
MX_UINT8 FCV_ST3 = (0x0);




//LCDDisplay(0): //Defines:

/**** Macro Substitutions ****
a = Unique Component Reference Number
b = D1 Port Letter
c = D2 Port Letter
d = D3 Port Letter
e = D4 Port Letter
f = RS Port Letter
g = E Port Letter
h = Data 1_Pin
i = Data 2 Pin
j = Data 3 Pin
k = Data 4 Pin
l = RS Pin
m = Enable Pin
n = Row Count
o = Column Count
******************************/

	//component connections
	//Port pin lat workaround for 8-bit PIC devices running >= 32MHz
	//seems we need this mod for 19660800 16F1937 so changed to >= 16MHz

  #ifdef FC_CAL_PIC
   #if MX_CLK_SPEED >= 32000000
	#define LCD_1__PORT0    latb
	#define LCD_1__PORT1    latb
	#define LCD_1__PORT2    latb
	#define LCD_1__PORT3    latb
	#define LCD_1__PORT4    latb
	#define LCD_1__PORT5    latb
   #else
    #ifdef MX_LCD_PORT_LAT
	 #define LCD_1__PORT0    latb
	 #define LCD_1__PORT1    latb
	 #define LCD_1__PORT2    latb
	 #define LCD_1__PORT3    latb
	 #define LCD_1__PORT4    latb
	 #define LCD_1__PORT5    latb
    #else
	 #define LCD_1__PORT0    portb
	 #define LCD_1__PORT1    portb
	 #define LCD_1__PORT2    portb
	 #define LCD_1__PORT3    portb
	 #define LCD_1__PORT4    portb
	 #define LCD_1__PORT5    portb
	#endif
   #endif
  #else
	#define LCD_1__PORT0    portb
	#define LCD_1__PORT1    portb
	#define LCD_1__PORT2    portb
	#define LCD_1__PORT3    portb
	#define LCD_1__PORT4    portb
	#define LCD_1__PORT5    portb
  #endif

	#define LCD_1__TRIS0    trisb
	#define LCD_1__TRIS1    trisb
	#define LCD_1__TRIS2    trisb
	#define LCD_1__TRIS3    trisb
	#define LCD_1__TRIS4    trisb
	#define LCD_1__TRIS5    trisb
	#define LCD_1__BIT0    	0
	#define LCD_1__BIT1    	1
	#define LCD_1__BIT2    	2
	#define LCD_1__BIT3    	3
	#define LCD_1__RS      	4
	#define LCD_1__E       	5
	#define LCD_1__ROWCNT	4
	#define LCD_1__COLCNT	16

	#ifdef _BOOSTC
	  #define LCD_1__DELAY   delay_10us(10)
	#endif
	#ifdef _C2C_
	  #define LCD_1__DELAY   delay_us(100)
	#endif
	#ifdef HI_TECH_C
	  #define LCD_1__DELAY   __delay_us(120)
	#endif
	#ifndef LCD_1__DELAY
	  #define LCD_1__DELAY   delay_us(100)
	#endif




//LCDDisplay(0): //Macro function declarations

void FCD_LCDDisplay0_RawSend(MX_UINT8 in, MX_UINT8 mask);
void FCD_LCDDisplay0_Start();
void FCD_LCDDisplay0_Clear();
void FCD_LCDDisplay0_PrintASCII(MX_UINT8 Character);
void FCD_LCDDisplay0_Command(MX_UINT8 in);
void FCD_LCDDisplay0_Cursor(MX_UINT8 x, MX_UINT8 y);
void FCD_LCDDisplay0_PrintNumber(MX_SINT16 Number);
void FCD_LCDDisplay0_PrintString(MX_STRING String, MX_UINT8 MSZ_String);
void FCD_LCDDisplay0_ScrollDisplay(MX_UINT8 Direction, MX_UINT8 Num_Positions);
void FCD_LCDDisplay0_ClearLine(MX_UINT8 Line);
void FCD_LCDDisplay0_RAM_Write(MX_UINT8 nIdx, MX_UINT8 d0, MX_UINT8 d1, MX_UINT8 d2, MX_UINT8 d3, MX_UINT8 d4, MX_UINT8 d5, MX_UINT8 d6, MX_UINT8 d7);


//SWITCH(0): //Defines:

/**** Macro Substitutions ****
a = Unique Reference
b = Switch Port Letter
c = Switch Pin Number
d = Switch Polarity Control
e = Switch Debounce Delay Value (us)
******************************/

#define Switch_2_SW_PORT		porta
#define Switch_2_SW_TRIS		trisa
#define Switch_2_SW_PIN		1
#define Switch_2_SW_POLE		(1 - 0) << 1

//Work out a schema for debounce delays
#define Switch_2_SW_DELAY		0 * 90					//90% + overhead
#define Switch_2_SW_DEL		delay_us(10)

#if (Switch_2_SW_DELAY > 65535)
	#undef Switch_2_SW_DELAY
	#undef Switch_2_SW_DEL
	#define Switch_2_SW_DELAY		0 * 9				//90% + overhead
	#define Switch_2_SW_DEL		delay_us(100)
	#if (Switch_2_SW_DELAY > 65535)
		#undef Switch_2_SW_DELAY
		#undef Switch_2_SW_DEL
		#define Switch_2_SW_DELAY		0
		#define Switch_2_SW_DEL		delay_ms(1)
		#if (Switch_2_SW_DELAY > 65535)
			#error "Switch Switch_2 Debounce Delay Too Large."
		#endif
	#endif
#endif




//SWITCH(0): //Macro function declarations

MX_UINT8 FCD_SWITCH0_ReadState();
void FCD_SWITCH0_WaitUntilHigh();
void FCD_SWITCH0_WaitUntilLow();


//SWITCH(1): //Defines:

/**** Macro Substitutions ****
a = Unique Reference
b = Switch Port Letter
c = Switch Pin Number
d = Switch Polarity Control
e = Switch Debounce Delay Value (us)
******************************/

#define Switch_3_SW_PORT		porta
#define Switch_3_SW_TRIS		trisa
#define Switch_3_SW_PIN		0
#define Switch_3_SW_POLE		(1 - 0) << 0

//Work out a schema for debounce delays
#define Switch_3_SW_DELAY		0 * 90					//90% + overhead
#define Switch_3_SW_DEL		delay_us(10)

#if (Switch_3_SW_DELAY > 65535)
	#undef Switch_3_SW_DELAY
	#undef Switch_3_SW_DEL
	#define Switch_3_SW_DELAY		0 * 9				//90% + overhead
	#define Switch_3_SW_DEL		delay_us(100)
	#if (Switch_3_SW_DELAY > 65535)
		#undef Switch_3_SW_DELAY
		#undef Switch_3_SW_DEL
		#define Switch_3_SW_DELAY		0
		#define Switch_3_SW_DEL		delay_ms(1)
		#if (Switch_3_SW_DELAY > 65535)
			#error "Switch Switch_3 Debounce Delay Too Large."
		#endif
	#endif
#endif




//SWITCH(1): //Macro function declarations

MX_UINT8 FCD_SWITCH1_ReadState();
void FCD_SWITCH1_WaitUntilHigh();
void FCD_SWITCH1_WaitUntilLow();


//SWITCH(2): //Defines:

/**** Macro Substitutions ****
a = Unique Reference
b = Switch Port Letter
c = Switch Pin Number
d = Switch Polarity Control
e = Switch Debounce Delay Value (us)
******************************/

#define Switch_4_SW_PORT		porta
#define Switch_4_SW_TRIS		trisa
#define Switch_4_SW_PIN		2
#define Switch_4_SW_POLE		(1 - 0) << 2

//Work out a schema for debounce delays
#define Switch_4_SW_DELAY		0 * 90					//90% + overhead
#define Switch_4_SW_DEL		delay_us(10)

#if (Switch_4_SW_DELAY > 65535)
	#undef Switch_4_SW_DELAY
	#undef Switch_4_SW_DEL
	#define Switch_4_SW_DELAY		0 * 9				//90% + overhead
	#define Switch_4_SW_DEL		delay_us(100)
	#if (Switch_4_SW_DELAY > 65535)
		#undef Switch_4_SW_DELAY
		#undef Switch_4_SW_DEL
		#define Switch_4_SW_DELAY		0
		#define Switch_4_SW_DEL		delay_ms(1)
		#if (Switch_4_SW_DELAY > 65535)
			#error "Switch Switch_4 Debounce Delay Too Large."
		#endif
	#endif
#endif




//SWITCH(2): //Macro function declarations

MX_UINT8 FCD_SWITCH2_ReadState();
void FCD_SWITCH2_WaitUntilHigh();
void FCD_SWITCH2_WaitUntilLow();



//LCDDisplay(0): //Macro implementations


void FCD_LCDDisplay0_RawSend(MX_UINT8 in, MX_UINT8 mask)
{
	
		MX_UINT8 pt;

		FC_CAL_Bit_Low(LCD_1__PORT0, LCD_1__BIT0);
		FC_CAL_Bit_Low(LCD_1__PORT1, LCD_1__BIT1);
		FC_CAL_Bit_Low(LCD_1__PORT2, LCD_1__BIT2);
		FC_CAL_Bit_Low(LCD_1__PORT3, LCD_1__BIT3);
		FC_CAL_Bit_Low(LCD_1__PORT4, LCD_1__RS);
		FC_CAL_Bit_Low(LCD_1__PORT5, LCD_1__E);
		pt = ((in >> 4) & 0x0f);
		if (pt & 0x01)
		    FC_CAL_Bit_High(LCD_1__PORT0, LCD_1__BIT0);
		if (pt & 0x02)
		    FC_CAL_Bit_High(LCD_1__PORT1, LCD_1__BIT1);
		if (pt & 0x04)
		    FC_CAL_Bit_High(LCD_1__PORT2, LCD_1__BIT2);
		if (pt & 0x08)
		    FC_CAL_Bit_High(LCD_1__PORT3, LCD_1__BIT3);
		if (mask)
		    FC_CAL_Bit_High(LCD_1__PORT4, LCD_1__RS);
		LCD_1__DELAY;
		FC_CAL_Bit_High (LCD_1__PORT5, LCD_1__E);
		LCD_1__DELAY;
		FC_CAL_Bit_Low (LCD_1__PORT5, LCD_1__E);
		pt = (in & 0x0f);
		LCD_1__DELAY;
		FC_CAL_Bit_Low(LCD_1__PORT0, LCD_1__BIT0);
		FC_CAL_Bit_Low(LCD_1__PORT1, LCD_1__BIT1);
		FC_CAL_Bit_Low(LCD_1__PORT2, LCD_1__BIT2);
		FC_CAL_Bit_Low(LCD_1__PORT3, LCD_1__BIT3);
		FC_CAL_Bit_Low(LCD_1__PORT4, LCD_1__RS);
		FC_CAL_Bit_Low(LCD_1__PORT5, LCD_1__E);
		if (pt & 0x01)
		    FC_CAL_Bit_High(LCD_1__PORT0, LCD_1__BIT0);
		if (pt & 0x02)
		    FC_CAL_Bit_High(LCD_1__PORT1, LCD_1__BIT1);
		if (pt & 0x04)
		    FC_CAL_Bit_High(LCD_1__PORT2, LCD_1__BIT2);
		if (pt & 0x08)
		    FC_CAL_Bit_High(LCD_1__PORT3, LCD_1__BIT3);
		if (mask)
		    FC_CAL_Bit_High(LCD_1__PORT4, LCD_1__RS);
		LCD_1__DELAY;
		FC_CAL_Bit_High (LCD_1__PORT5, LCD_1__E);
		LCD_1__DELAY;
		FC_CAL_Bit_Low (LCD_1__PORT5, LCD_1__E);
		LCD_1__DELAY;

}

void FCD_LCDDisplay0_Start()
{
	
		FC_CAL_Bit_Low_DDR(LCD_1__PORT0, LCD_1__TRIS0, LCD_1__BIT0);
		FC_CAL_Bit_Low_DDR(LCD_1__PORT1, LCD_1__TRIS1, LCD_1__BIT1);
		FC_CAL_Bit_Low_DDR(LCD_1__PORT2, LCD_1__TRIS2, LCD_1__BIT2);
		FC_CAL_Bit_Low_DDR(LCD_1__PORT3, LCD_1__TRIS3, LCD_1__BIT3);
		FC_CAL_Bit_Low_DDR(LCD_1__PORT4, LCD_1__TRIS4, LCD_1__RS);
		FC_CAL_Bit_Low_DDR(LCD_1__PORT5, LCD_1__TRIS5, LCD_1__E);

		Wdt_Delay_Ms(12);

		FCD_LCDDisplay0_RawSend(0x33, 0);
		Wdt_Delay_Ms(2);
		FCD_LCDDisplay0_RawSend(0x33, 0);
		Wdt_Delay_Ms(2);
		FCD_LCDDisplay0_RawSend(0x32, 0);
		Wdt_Delay_Ms(2);
		FCD_LCDDisplay0_RawSend(0x2c, 0);
		Wdt_Delay_Ms(2);
		FCD_LCDDisplay0_RawSend(0x06, 0);
		Wdt_Delay_Ms(2);
		FCD_LCDDisplay0_RawSend(0x0c, 0);
		Wdt_Delay_Ms(2);

		//clear the display
		FCD_LCDDisplay0_RawSend(0x01, 0);
		Wdt_Delay_Ms(2);
		FCD_LCDDisplay0_RawSend(0x02, 0);
		Wdt_Delay_Ms(2);

}

void FCD_LCDDisplay0_Clear()
{
	
		FCD_LCDDisplay0_RawSend(0x01, 0);
		Wdt_Delay_Ms(2);
		FCD_LCDDisplay0_RawSend(0x02, 0);
		Wdt_Delay_Ms(2);

}

void FCD_LCDDisplay0_PrintASCII(MX_UINT8 Character)
{
	
		FCD_LCDDisplay0_RawSend(Character, 0x10);

}

void FCD_LCDDisplay0_Command(MX_UINT8 in)
{
	
		FCD_LCDDisplay0_RawSend(in, 0);
		Wdt_Delay_Ms(2);

}

void FCD_LCDDisplay0_Cursor(MX_UINT8 x, MX_UINT8 y)
{
	
	  #if (LCD_1__ROWCNT == 1)
	    y=0x80;
	  #endif

	  #if (LCD_1__ROWCNT == 2)
		if (y==0)
			y=0x80;
		else
			y=0xc0;
	  #endif

	  #if (LCD_1__ROWCNT == 4)
		if (y==0)
			y=0x80;
		else if (y==1)
			y=0xc0;

		#if (LCD_1__COLCNT == 16)
			else if (y==2)
				y=0x90;
			else
				y=0xd0;
		#endif

		#if (LCD_1__COLCNT == 20)
			else if (y==2)
				y=0x94;
			else
				y=0xd4;
		#endif
	  #endif

		FCD_LCDDisplay0_RawSend(y+x, 0);
		Wdt_Delay_Ms(2);

}

void FCD_LCDDisplay0_PrintNumber(MX_SINT16 Number)
{
	
		MX_SINT16 tmp_int;
		MX_UINT8 tmp_byte;

		if (Number < 0)
		{
			FCD_LCDDisplay0_RawSend('-', 0x10);
			Number = 0 - Number;
		}

		tmp_int = Number;
		if (Number >= 10000)
		{
			tmp_byte = tmp_int / 10000;
			FCD_LCDDisplay0_RawSend('0' + tmp_byte, 0x10);

			while (tmp_byte > 0)
			{
				tmp_int = tmp_int - 10000;
				tmp_byte--;
			}
		}
		if (Number >= 1000)
		{
			tmp_byte = tmp_int / 1000;
			FCD_LCDDisplay0_RawSend('0' + tmp_byte, 0x10);

			while (tmp_byte > 0)
			{
				tmp_int = tmp_int - 1000;
				tmp_byte--;
			}
		}
		if (Number >= 100)
		{
			tmp_byte = tmp_int / 100;
			FCD_LCDDisplay0_RawSend('0' + tmp_byte, 0x10);

			while (tmp_byte > 0)
			{
				tmp_int = tmp_int - 100;
				tmp_byte--;
			}
		}
		if (Number >= 10)
		{
			tmp_byte = tmp_int / 10;
			FCD_LCDDisplay0_RawSend('0' + tmp_byte, 0x10);

			while (tmp_byte > 0)
			{
				tmp_int = tmp_int - 10;
				tmp_byte--;
			}
		}
		FCD_LCDDisplay0_RawSend('0' + tmp_int, 0x10);

}

void FCD_LCDDisplay0_PrintString(MX_STRING String, MX_UINT8 MSZ_String)
{
	
		MX_UINT8 idx = 0;

		for (idx=0; idx<MSZ_String; idx++)
		{
			if (String[idx] == 0)
			{
				break;
			}
			FCD_LCDDisplay0_RawSend(String[idx], 0x10);
		}

}

void FCD_LCDDisplay0_ScrollDisplay(MX_UINT8 Direction, MX_UINT8 Num_Positions)
{
	
		MX_UINT8 cmd = 0;
		MX_UINT8 count;

		//Choose the direction
		switch (Direction)
		{
			case 0:
			case 'l':
			case 'L':

				cmd = 0x18;
				break;

			case 1:
			case 'r':
			case 'R':

				cmd = 0x1C;
				break;

			default:
				break;
		}

		//If direction accepted then scroll the specified amount
		if (cmd)
		{
			for (count = 0; count < Num_Positions; count++)
				FCD_LCDDisplay0_Command(cmd);
		}

}

void FCD_LCDDisplay0_ClearLine(MX_UINT8 Line)
{
	
		MX_UINT8 count;
		MX_UINT8 rowcount;

		//Define number of columns per line
		#if (LCD_1__ROWCNT == 1)
			rowcount=80;
		#endif

		#if (LCD_1__ROWCNT == 2)
			rowcount=40;
		#endif

		#if (LCD_1__ROWCNT == 4)
			#if (LCD_1__COLCNT == 16)
				rowcount=16;
			#endif
			#if (LCD_1__COLCNT == 20)
				rowcount=20;
			#endif
		#endif

		//Start at beginning of the line
		FCD_LCDDisplay0_Cursor (0, Line);

		//Send out spaces to clear line
		for (count = 0; count < rowcount; count++)
			FCD_LCDDisplay0_RawSend(' ', 0x10);

		//Move back to the beginning of the line.
		FCD_LCDDisplay0_Cursor (0, Line);

}

void FCD_LCDDisplay0_RAM_Write(MX_UINT8 nIdx, MX_UINT8 d0, MX_UINT8 d1, MX_UINT8 d2, MX_UINT8 d3, MX_UINT8 d4, MX_UINT8 d5, MX_UINT8 d6, MX_UINT8 d7)
{
	   //set CGRAM address

	   FCD_LCDDisplay0_RawSend(64 + (nIdx << 3), 0);
	   delay_ms(2);

	   //write CGRAM data
	   FCD_LCDDisplay0_RawSend(d0, 0x10);
	   FCD_LCDDisplay0_RawSend(d1, 0x10);
	   FCD_LCDDisplay0_RawSend(d2, 0x10);
	   FCD_LCDDisplay0_RawSend(d3, 0x10);
	   FCD_LCDDisplay0_RawSend(d4, 0x10);
	   FCD_LCDDisplay0_RawSend(d5, 0x10);
	   FCD_LCDDisplay0_RawSend(d6, 0x10);
	   FCD_LCDDisplay0_RawSend(d7, 0x10);

	   //Clear the display
	   FCD_LCDDisplay0_RawSend(0x01, 0);
	   delay_ms(2);
	   FCD_LCDDisplay0_RawSend(0x02, 0);
	   delay_ms(2);

}



//SWITCH(0): //Macro implementations


MX_UINT8 FCD_SWITCH0_ReadState()
{
	
		MX_UINT8 switchval = 255;

	  #if Switch_2_SW_DELAY > 0
		MX_UINT16 del_count;
		MX_UINT8 old_switchval;
	  #endif

		FC_CAL_Bit_In_DDR( Switch_2_SW_PORT , Switch_2_SW_TRIS , Switch_2_SW_PIN );		//Convert pin to input
		switchval = FC_CAL_Bit_In( Switch_2_SW_PORT , Switch_2_SW_PIN );			//Sample input

	  #if (Switch_2_SW_POLE == 0)
		if (switchval)													//Invert logic if required
			switchval = 0;
		else
			switchval = 1;
	  #endif

	  #if (Switch_2_SW_DELAY > 0)

		del_count = 0;
		old_switchval = 255;

		while (del_count < Switch_2_SW_DELAY)									//Debounce input
		{
			Switch_2_SW_DEL;
			switchval = FC_CAL_Bit_In( Switch_2_SW_PORT , Switch_2_SW_PIN );		//Sample input

		  #if (Switch_2_SW_POLE == 0)
			if (switchval)												//Invert logic if required
				switchval = 0;
			else
				switchval = 1;
		  #endif

			if (switchval == old_switchval)								//Is switch the same state?
				del_count++;											//Increment counter
			else
				del_count = 0;											//Else reset counter

			old_switchval = switchval;									//Update the old state
		}
	  #endif

		return (switchval);												//Return state of switch as least significant bit

}

void FCD_SWITCH0_WaitUntilHigh()
{
	
		MX_UINT8 switchval = 255;

	  #if Switch_2_SW_DELAY > 0
		MX_UINT16 del_count;
		MX_UINT8 old_switchval;
	  #endif

		FC_CAL_Bit_In_DDR ( Switch_2_SW_PORT , Switch_2_SW_TRIS , Switch_2_SW_PIN );

		while (switchval != Switch_2_SW_POLE)										//While state not active
		{
			switchval = FC_CAL_Bit_In ( Switch_2_SW_PORT, Switch_2_SW_PIN );			//Convert pin to input

		  #if (Switch_2_SW_DELAY > 0)

		  	del_count = 0;
		  	old_switchval = 255;

			while (del_count < Switch_2_SW_DELAY)									//Debounce input
			{
				Switch_2_SW_DEL;
				switchval = FC_CAL_Bit_In ( Switch_2_SW_PORT , Switch_2_SW_PIN );		//Sample input

				if (switchval == old_switchval)								//Is switch the same state?
					del_count++;											//Increment counter
				else
					del_count = 0;											//Else reset counter

				old_switchval = switchval;									//Update the old state
			}
		  #endif
		}

}

void FCD_SWITCH0_WaitUntilLow()
{
	
		MX_UINT8 switchval = Switch_2_SW_POLE;

	  #if Switch_2_SW_DELAY > 0
		MX_UINT16 del_count = 0;
		MX_UINT8 old_switchval;
	  #endif

		FC_CAL_Bit_In_DDR ( Switch_2_SW_PORT, Switch_2_SW_TRIS , Switch_2_SW_PIN );			//Convert pin to input

		while (switchval == Switch_2_SW_POLE)										//While state active
		{
			switchval = FC_CAL_Bit_In ( Switch_2_SW_PORT, Switch_2_SW_PIN );			//Sample input

		  #if (Switch_2_SW_DELAY > 0)

		  	del_count = 0;
		  	old_switchval = 255;

			while (del_count < Switch_2_SW_DELAY)									//Debounce input
			{
				Switch_2_SW_DEL;
				switchval = FC_CAL_Bit_In ( Switch_2_SW_PORT, Switch_2_SW_PIN );		//Sample input

				if (switchval == old_switchval)								//Is switch the same state?
					del_count++;											//Increment counter
				else
					del_count = 0;											//Else reset counter

				old_switchval = switchval;									//Update the old state
			}
		  #endif
		}

}



//SWITCH(1): //Macro implementations


MX_UINT8 FCD_SWITCH1_ReadState()
{
	
		MX_UINT8 switchval = 255;

	  #if Switch_3_SW_DELAY > 0
		MX_UINT16 del_count;
		MX_UINT8 old_switchval;
	  #endif

		FC_CAL_Bit_In_DDR( Switch_3_SW_PORT , Switch_3_SW_TRIS , Switch_3_SW_PIN );		//Convert pin to input
		switchval = FC_CAL_Bit_In( Switch_3_SW_PORT , Switch_3_SW_PIN );			//Sample input

	  #if (Switch_3_SW_POLE == 0)
		if (switchval)													//Invert logic if required
			switchval = 0;
		else
			switchval = 1;
	  #endif

	  #if (Switch_3_SW_DELAY > 0)

		del_count = 0;
		old_switchval = 255;

		while (del_count < Switch_3_SW_DELAY)									//Debounce input
		{
			Switch_3_SW_DEL;
			switchval = FC_CAL_Bit_In( Switch_3_SW_PORT , Switch_3_SW_PIN );		//Sample input

		  #if (Switch_3_SW_POLE == 0)
			if (switchval)												//Invert logic if required
				switchval = 0;
			else
				switchval = 1;
		  #endif

			if (switchval == old_switchval)								//Is switch the same state?
				del_count++;											//Increment counter
			else
				del_count = 0;											//Else reset counter

			old_switchval = switchval;									//Update the old state
		}
	  #endif

		return (switchval);												//Return state of switch as least significant bit

}

void FCD_SWITCH1_WaitUntilHigh()
{
	
		MX_UINT8 switchval = 255;

	  #if Switch_3_SW_DELAY > 0
		MX_UINT16 del_count;
		MX_UINT8 old_switchval;
	  #endif

		FC_CAL_Bit_In_DDR ( Switch_3_SW_PORT , Switch_3_SW_TRIS , Switch_3_SW_PIN );

		while (switchval != Switch_3_SW_POLE)										//While state not active
		{
			switchval = FC_CAL_Bit_In ( Switch_3_SW_PORT, Switch_3_SW_PIN );			//Convert pin to input

		  #if (Switch_3_SW_DELAY > 0)

		  	del_count = 0;
		  	old_switchval = 255;

			while (del_count < Switch_3_SW_DELAY)									//Debounce input
			{
				Switch_3_SW_DEL;
				switchval = FC_CAL_Bit_In ( Switch_3_SW_PORT , Switch_3_SW_PIN );		//Sample input

				if (switchval == old_switchval)								//Is switch the same state?
					del_count++;											//Increment counter
				else
					del_count = 0;											//Else reset counter

				old_switchval = switchval;									//Update the old state
			}
		  #endif
		}

}

void FCD_SWITCH1_WaitUntilLow()
{
	
		MX_UINT8 switchval = Switch_3_SW_POLE;

	  #if Switch_3_SW_DELAY > 0
		MX_UINT16 del_count = 0;
		MX_UINT8 old_switchval;
	  #endif

		FC_CAL_Bit_In_DDR ( Switch_3_SW_PORT, Switch_3_SW_TRIS , Switch_3_SW_PIN );			//Convert pin to input

		while (switchval == Switch_3_SW_POLE)										//While state active
		{
			switchval = FC_CAL_Bit_In ( Switch_3_SW_PORT, Switch_3_SW_PIN );			//Sample input

		  #if (Switch_3_SW_DELAY > 0)

		  	del_count = 0;
		  	old_switchval = 255;

			while (del_count < Switch_3_SW_DELAY)									//Debounce input
			{
				Switch_3_SW_DEL;
				switchval = FC_CAL_Bit_In ( Switch_3_SW_PORT, Switch_3_SW_PIN );		//Sample input

				if (switchval == old_switchval)								//Is switch the same state?
					del_count++;											//Increment counter
				else
					del_count = 0;											//Else reset counter

				old_switchval = switchval;									//Update the old state
			}
		  #endif
		}

}



//SWITCH(2): //Macro implementations


MX_UINT8 FCD_SWITCH2_ReadState()
{
	
		MX_UINT8 switchval = 255;

	  #if Switch_4_SW_DELAY > 0
		MX_UINT16 del_count;
		MX_UINT8 old_switchval;
	  #endif

		FC_CAL_Bit_In_DDR( Switch_4_SW_PORT , Switch_4_SW_TRIS , Switch_4_SW_PIN );		//Convert pin to input
		switchval = FC_CAL_Bit_In( Switch_4_SW_PORT , Switch_4_SW_PIN );			//Sample input

	  #if (Switch_4_SW_POLE == 0)
		if (switchval)													//Invert logic if required
			switchval = 0;
		else
			switchval = 1;
	  #endif

	  #if (Switch_4_SW_DELAY > 0)

		del_count = 0;
		old_switchval = 255;

		while (del_count < Switch_4_SW_DELAY)									//Debounce input
		{
			Switch_4_SW_DEL;
			switchval = FC_CAL_Bit_In( Switch_4_SW_PORT , Switch_4_SW_PIN );		//Sample input

		  #if (Switch_4_SW_POLE == 0)
			if (switchval)												//Invert logic if required
				switchval = 0;
			else
				switchval = 1;
		  #endif

			if (switchval == old_switchval)								//Is switch the same state?
				del_count++;											//Increment counter
			else
				del_count = 0;											//Else reset counter

			old_switchval = switchval;									//Update the old state
		}
	  #endif

		return (switchval);												//Return state of switch as least significant bit

}

void FCD_SWITCH2_WaitUntilHigh()
{
	
		MX_UINT8 switchval = 255;

	  #if Switch_4_SW_DELAY > 0
		MX_UINT16 del_count;
		MX_UINT8 old_switchval;
	  #endif

		FC_CAL_Bit_In_DDR ( Switch_4_SW_PORT , Switch_4_SW_TRIS , Switch_4_SW_PIN );

		while (switchval != Switch_4_SW_POLE)										//While state not active
		{
			switchval = FC_CAL_Bit_In ( Switch_4_SW_PORT, Switch_4_SW_PIN );			//Convert pin to input

		  #if (Switch_4_SW_DELAY > 0)

		  	del_count = 0;
		  	old_switchval = 255;

			while (del_count < Switch_4_SW_DELAY)									//Debounce input
			{
				Switch_4_SW_DEL;
				switchval = FC_CAL_Bit_In ( Switch_4_SW_PORT , Switch_4_SW_PIN );		//Sample input

				if (switchval == old_switchval)								//Is switch the same state?
					del_count++;											//Increment counter
				else
					del_count = 0;											//Else reset counter

				old_switchval = switchval;									//Update the old state
			}
		  #endif
		}

}

void FCD_SWITCH2_WaitUntilLow()
{
	
		MX_UINT8 switchval = Switch_4_SW_POLE;

	  #if Switch_4_SW_DELAY > 0
		MX_UINT16 del_count = 0;
		MX_UINT8 old_switchval;
	  #endif

		FC_CAL_Bit_In_DDR ( Switch_4_SW_PORT, Switch_4_SW_TRIS , Switch_4_SW_PIN );			//Convert pin to input

		while (switchval == Switch_4_SW_POLE)										//While state active
		{
			switchval = FC_CAL_Bit_In ( Switch_4_SW_PORT, Switch_4_SW_PIN );			//Sample input

		  #if (Switch_4_SW_DELAY > 0)

		  	del_count = 0;
		  	old_switchval = 255;

			while (del_count < Switch_4_SW_DELAY)									//Debounce input
			{
				Switch_4_SW_DEL;
				switchval = FC_CAL_Bit_In ( Switch_4_SW_PORT, Switch_4_SW_PIN );		//Sample input

				if (switchval == old_switchval)								//Is switch the same state?
					del_count++;											//Increment counter
				else
					del_count = 0;											//Else reset counter

				old_switchval = switchval;									//Update the old state
			}
		  #endif
		}

}

#include "C:\Program Files (x86)\Flowcode\v5\CAL\includes.c"

//Macro implementations



void main()
{
	//Initialization
	ansel = 0;
anselh = 0;


	//Interrupt initialization code
	option_reg = 0xC0;


	//Call Component Macro
	//Call Component Macro: Start()
	FCD_LCDDisplay0_Start();

	//Loop
	//Loop: While 1
	while (1)
	{

		//Call Component Macro
		//Call Component Macro: start=ReadState()
		FCV_START = FCD_SWITCH0_ReadState();

		//Decision
		//Decision: min < 10?
		if (FCV_MIN < 10)
		{

			//Call Component Macro
			//Call Component Macro: Cursor(5, 0)
			FCD_LCDDisplay0_Cursor(5, 0);

			//Call Component Macro
			//Call Component Macro: PrintNumber(min1)
			FCD_LCDDisplay0_PrintNumber(FCV_MIN1);

			//Call Component Macro
			//Call Component Macro: Cursor(4, 0)
			FCD_LCDDisplay0_Cursor(4, 0);

			//Call Component Macro
			//Call Component Macro: PrintNumber(min)
			FCD_LCDDisplay0_PrintNumber(FCV_MIN);

		} else {

			//Call Component Macro
			//Call Component Macro: Cursor(5, 0)
			FCD_LCDDisplay0_Cursor(5, 0);

			//Call Component Macro
			//Call Component Macro: PrintNumber(min)
			FCD_LCDDisplay0_PrintNumber(FCV_MIN);

		}

		//Call Component Macro
		//Call Component Macro: Cursor(6, 0)
		FCD_LCDDisplay0_Cursor(6, 0);

		//Call Component Macro
		//Call Component Macro: PrintString(":")
		FCD_LCDDisplay0_PrintString(":", 1);

		//Decision
		//Decision: sek < 10?
		if (FCV_SEK < 10)
		{

			//Call Component Macro
			//Call Component Macro: Cursor(8, 0)
			FCD_LCDDisplay0_Cursor(8, 0);

			//Call Component Macro
			//Call Component Macro: PrintNumber(sek)
			FCD_LCDDisplay0_PrintNumber(FCV_SEK);

			//Call Component Macro
			//Call Component Macro: Cursor(7, 0)
			FCD_LCDDisplay0_Cursor(7, 0);

			//Call Component Macro
			//Call Component Macro: PrintNumber(sek1)
			FCD_LCDDisplay0_PrintNumber(FCV_SEK1);

		} else {

			//Call Component Macro
			//Call Component Macro: Cursor(7, 0)
			FCD_LCDDisplay0_Cursor(7, 0);

			//Call Component Macro
			//Call Component Macro: PrintNumber(sek)
			FCD_LCDDisplay0_PrintNumber(FCV_SEK);

		}

		//Call Component Macro
		//Call Component Macro: Cursor(9, 0)
		FCD_LCDDisplay0_Cursor(9, 0);

		//Call Component Macro
		//Call Component Macro: PrintString(":")
		FCD_LCDDisplay0_PrintString(":", 1);

		//Decision
		//Decision: sto < 10?
		if (FCV_STO < 10)
		{

			//Call Component Macro
			//Call Component Macro: Cursor(11, 0)
			FCD_LCDDisplay0_Cursor(11, 0);

			//Call Component Macro
			//Call Component Macro: PrintNumber(sto)
			FCD_LCDDisplay0_PrintNumber(FCV_STO);

			//Call Component Macro
			//Call Component Macro: Cursor(10, 0)
			FCD_LCDDisplay0_Cursor(10, 0);

			//Call Component Macro
			//Call Component Macro: PrintNumber(sto1)
			FCD_LCDDisplay0_PrintNumber(FCV_STO1);

		} else {

			//Call Component Macro
			//Call Component Macro: Cursor(10, 0)
			FCD_LCDDisplay0_Cursor(10, 0);

			//Call Component Macro
			//Call Component Macro: PrintNumber(sto)
			FCD_LCDDisplay0_PrintNumber(FCV_STO);

		}

		//Decision
		//Decision: start == 1?
		if (FCV_START == 1)
		{

			//Calculation
			//Calculation:
			//  st1 = st1 + 1
			//  st2 = 0
			//  st3 = 0
			FCV_ST1 = FCV_ST1 + 1;
			FCV_ST2 = 0;
			FCV_ST3 = 0;

		// } else {

		}

		//Loop
		//Loop: While st1 > 0 AND st2 == 0 AND st3 == 0
		while (FCV_ST1 > 0 & FCV_ST2 == 0 & FCV_ST3 == 0)
		{

			//Call Component Macro
			//Call Component Macro: stop=ReadState()
			FCV_STOP = FCD_SWITCH1_ReadState();

			//Call Component Macro
			//Call Component Macro: restart=ReadState()
			FCV_RESTART = FCD_SWITCH2_ReadState();

			//Call Component Macro
			//Call Component Macro: start=ReadState()
			FCV_START = FCD_SWITCH0_ReadState();

			//Decision
			//Decision: stop == 1?
			if (FCV_STOP == 1)
			{

				//Calculation
				//Calculation:
				//  st1 = 0
				//  st2 = 1
				//  st3 = 0
				FCV_ST1 = 0;
				FCV_ST2 = 1;
				FCV_ST3 = 0;

			// } else {

			}

			//Decision
			//Decision: restart == 1?
			if (FCV_RESTART == 1)
			{

				//Calculation
				//Calculation:
				//  st1 = 0
				//  st2 = 0
				//  st3 = 1
				FCV_ST1 = 0;
				FCV_ST2 = 0;
				FCV_ST3 = 1;

			// } else {

			}

			//Decision
			//Decision: start == 1?
			if (FCV_START == 1)
			{

				//Calculation
				//Calculation:
				//  st1 = st1 + 1
				//  st2 = 0
				//  st3 = 0
				FCV_ST1 = FCV_ST1 + 1;
				FCV_ST2 = 0;
				FCV_ST3 = 0;

			// } else {

			}

			//Decision
			//Decision: st1 == 2?
			if (FCV_ST1 == 2)
			{

				//Decision
				//Decision: min < 10?
				if (FCV_MIN < 10)
				{

					//Call Component Macro
					//Call Component Macro: Cursor(5, st1-1)
					FCD_LCDDisplay0_Cursor(5, FCV_ST1 - 1);

					//Call Component Macro
					//Call Component Macro: PrintNumber(min1)
					FCD_LCDDisplay0_PrintNumber(FCV_MIN1);

					//Call Component Macro
					//Call Component Macro: Cursor(4, st1-1)
					FCD_LCDDisplay0_Cursor(4, FCV_ST1 - 1);

					//Call Component Macro
					//Call Component Macro: PrintNumber(min)
					FCD_LCDDisplay0_PrintNumber(FCV_MIN);

				} else {

					//Call Component Macro
					//Call Component Macro: Cursor(5, st1-1)
					FCD_LCDDisplay0_Cursor(5, FCV_ST1 - 1);

					//Call Component Macro
					//Call Component Macro: PrintNumber(min)
					FCD_LCDDisplay0_PrintNumber(FCV_MIN);

				}

				//Call Component Macro
				//Call Component Macro: Cursor(6, st1-1)
				FCD_LCDDisplay0_Cursor(6, FCV_ST1 - 1);

				//Call Component Macro
				//Call Component Macro: PrintString(":")
				FCD_LCDDisplay0_PrintString(":", 1);

				//Decision
				//Decision: sek < 10?
				if (FCV_SEK < 10)
				{

					//Call Component Macro
					//Call Component Macro: Cursor(8, st1-1)
					FCD_LCDDisplay0_Cursor(8, FCV_ST1 - 1);

					//Call Component Macro
					//Call Component Macro: PrintNumber(sek)
					FCD_LCDDisplay0_PrintNumber(FCV_SEK);

					//Call Component Macro
					//Call Component Macro: Cursor(7, st1-1)
					FCD_LCDDisplay0_Cursor(7, FCV_ST1 - 1);

					//Call Component Macro
					//Call Component Macro: PrintNumber(sek1)
					FCD_LCDDisplay0_PrintNumber(FCV_SEK1);

				} else {

					//Call Component Macro
					//Call Component Macro: Cursor(7, st1-1)
					FCD_LCDDisplay0_Cursor(7, FCV_ST1 - 1);

					//Call Component Macro
					//Call Component Macro: PrintNumber(sek)
					FCD_LCDDisplay0_PrintNumber(FCV_SEK);

				}

				//Call Component Macro
				//Call Component Macro: Cursor(9, st1-1)
				FCD_LCDDisplay0_Cursor(9, FCV_ST1 - 1);

				//Call Component Macro
				//Call Component Macro: PrintString(":")
				FCD_LCDDisplay0_PrintString(":", 1);

				//Decision
				//Decision: sto < 10?
				if (FCV_STO < 10)
				{

					//Call Component Macro
					//Call Component Macro: Cursor(11, st1-1)
					FCD_LCDDisplay0_Cursor(11, FCV_ST1 - 1);

					//Call Component Macro
					//Call Component Macro: PrintNumber(sto)
					FCD_LCDDisplay0_PrintNumber(FCV_STO);

					//Call Component Macro
					//Call Component Macro: Cursor(10, st1-1)
					FCD_LCDDisplay0_Cursor(10, FCV_ST1 - 1);

					//Call Component Macro
					//Call Component Macro: PrintNumber(sto1)
					FCD_LCDDisplay0_PrintNumber(FCV_STO1);

				} else {

					//Call Component Macro
					//Call Component Macro: Cursor(10, st1-1)
					FCD_LCDDisplay0_Cursor(10, FCV_ST1 - 1);

					//Call Component Macro
					//Call Component Macro: PrintNumber(sto)
					FCD_LCDDisplay0_PrintNumber(FCV_STO);

				}

			// } else {

			}

			//Decision
			//Decision: min < 10?
			if (FCV_MIN < 10)
			{

				//Call Component Macro
				//Call Component Macro: Cursor(5, 0)
				FCD_LCDDisplay0_Cursor(5, 0);

				//Call Component Macro
				//Call Component Macro: PrintNumber(min1)
				FCD_LCDDisplay0_PrintNumber(FCV_MIN1);

				//Call Component Macro
				//Call Component Macro: Cursor(4, 0)
				FCD_LCDDisplay0_Cursor(4, 0);

				//Call Component Macro
				//Call Component Macro: PrintNumber(min)
				FCD_LCDDisplay0_PrintNumber(FCV_MIN);

			} else {

				//Call Component Macro
				//Call Component Macro: Cursor(5, 0)
				FCD_LCDDisplay0_Cursor(5, 0);

				//Call Component Macro
				//Call Component Macro: PrintNumber(min)
				FCD_LCDDisplay0_PrintNumber(FCV_MIN);

			}

			//Call Component Macro
			//Call Component Macro: Cursor(6, 0)
			FCD_LCDDisplay0_Cursor(6, 0);

			//Call Component Macro
			//Call Component Macro: PrintString(":")
			FCD_LCDDisplay0_PrintString(":", 1);

			//Decision
			//Decision: sek < 10?
			if (FCV_SEK < 10)
			{

				//Call Component Macro
				//Call Component Macro: Cursor(8, 0)
				FCD_LCDDisplay0_Cursor(8, 0);

				//Call Component Macro
				//Call Component Macro: PrintNumber(sek)
				FCD_LCDDisplay0_PrintNumber(FCV_SEK);

				//Call Component Macro
				//Call Component Macro: Cursor(7, 0)
				FCD_LCDDisplay0_Cursor(7, 0);

				//Call Component Macro
				//Call Component Macro: PrintNumber(sek1)
				FCD_LCDDisplay0_PrintNumber(FCV_SEK1);

			} else {

				//Call Component Macro
				//Call Component Macro: Cursor(7, 0)
				FCD_LCDDisplay0_Cursor(7, 0);

				//Call Component Macro
				//Call Component Macro: PrintNumber(sek)
				FCD_LCDDisplay0_PrintNumber(FCV_SEK);

			}

			//Call Component Macro
			//Call Component Macro: Cursor(9, 0)
			FCD_LCDDisplay0_Cursor(9, 0);

			//Call Component Macro
			//Call Component Macro: PrintString(":")
			FCD_LCDDisplay0_PrintString(":", 1);

			//Decision
			//Decision: sto < 10?
			if (FCV_STO < 10)
			{

				//Call Component Macro
				//Call Component Macro: Cursor(11, 0)
				FCD_LCDDisplay0_Cursor(11, 0);

				//Call Component Macro
				//Call Component Macro: PrintNumber(sto)
				FCD_LCDDisplay0_PrintNumber(FCV_STO);

				//Call Component Macro
				//Call Component Macro: Cursor(10, 0)
				FCD_LCDDisplay0_Cursor(10, 0);

				//Call Component Macro
				//Call Component Macro: PrintNumber(sto1)
				FCD_LCDDisplay0_PrintNumber(FCV_STO1);

			} else {

				//Call Component Macro
				//Call Component Macro: Cursor(10, 0)
				FCD_LCDDisplay0_Cursor(10, 0);

				//Call Component Macro
				//Call Component Macro: PrintNumber(sto)
				FCD_LCDDisplay0_PrintNumber(FCV_STO);

			}

			//Delay
			//Delay: 1 ms
			delay_ms(1);

			//Calculation
			//Calculation:
			//  sto = sto + 1
			FCV_STO = FCV_STO + 1;

			//Decision
			//Decision: sto == 100?
			if (FCV_STO == 100)
			{

				//Calculation
				//Calculation:
				//  sto = 0
				//  sek = sek + 1
				FCV_STO = 0;
				FCV_SEK = FCV_SEK + 1;

				//Decision
				//Decision: sek == 60?
				if (FCV_SEK == 60)
				{

					//Calculation
					//Calculation:
					//  sek = 0
					//  min = min + 1
					FCV_SEK = 0;
					FCV_MIN = FCV_MIN + 1;

				// } else {

				}

			// } else {

			}


		}

		//Loop
		//Loop: While st1 == 0 AND st2 == 1 AND st3 == 0
		while (FCV_ST1 == 0 & FCV_ST2 == 1 & FCV_ST3 == 0)
		{

			//Call Component Macro
			//Call Component Macro: start=ReadState()
			FCV_START = FCD_SWITCH0_ReadState();

			//Call Component Macro
			//Call Component Macro: restart=ReadState()
			FCV_RESTART = FCD_SWITCH2_ReadState();

			//Decision
			//Decision: start == 1?
			if (FCV_START == 1)
			{

				//Calculation
				//Calculation:
				//  st1 = 1
				//  st2 = 0
				//  st3 = 0
				FCV_ST1 = 1;
				FCV_ST2 = 0;
				FCV_ST3 = 0;

			// } else {

			}

			//Decision
			//Decision: restart == 1?
			if (FCV_RESTART == 1)
			{

				//Calculation
				//Calculation:
				//  st1 = 0
				//  st2 = 0
				//  st3 = 1
				FCV_ST1 = 0;
				FCV_ST2 = 0;
				FCV_ST3 = 1;

			// } else {

			}

			//Decision
			//Decision: min < 10?
			if (FCV_MIN < 10)
			{

				//Call Component Macro
				//Call Component Macro: Cursor(5, 0)
				FCD_LCDDisplay0_Cursor(5, 0);

				//Call Component Macro
				//Call Component Macro: PrintNumber(min1)
				FCD_LCDDisplay0_PrintNumber(FCV_MIN1);

				//Call Component Macro
				//Call Component Macro: Cursor(4, 0)
				FCD_LCDDisplay0_Cursor(4, 0);

				//Call Component Macro
				//Call Component Macro: PrintNumber(min)
				FCD_LCDDisplay0_PrintNumber(FCV_MIN);

			} else {

				//Call Component Macro
				//Call Component Macro: Cursor(5, 0)
				FCD_LCDDisplay0_Cursor(5, 0);

				//Call Component Macro
				//Call Component Macro: PrintNumber(min)
				FCD_LCDDisplay0_PrintNumber(FCV_MIN);

			}

			//Call Component Macro
			//Call Component Macro: Cursor(6, 0)
			FCD_LCDDisplay0_Cursor(6, 0);

			//Call Component Macro
			//Call Component Macro: PrintString(":")
			FCD_LCDDisplay0_PrintString(":", 1);

			//Decision
			//Decision: sek < 10?
			if (FCV_SEK < 10)
			{

				//Call Component Macro
				//Call Component Macro: Cursor(8, 0)
				FCD_LCDDisplay0_Cursor(8, 0);

				//Call Component Macro
				//Call Component Macro: PrintNumber(sek)
				FCD_LCDDisplay0_PrintNumber(FCV_SEK);

				//Call Component Macro
				//Call Component Macro: Cursor(7, 0)
				FCD_LCDDisplay0_Cursor(7, 0);

				//Call Component Macro
				//Call Component Macro: PrintNumber(sek1)
				FCD_LCDDisplay0_PrintNumber(FCV_SEK1);

			} else {

				//Call Component Macro
				//Call Component Macro: Cursor(7, 0)
				FCD_LCDDisplay0_Cursor(7, 0);

				//Call Component Macro
				//Call Component Macro: PrintNumber(sek)
				FCD_LCDDisplay0_PrintNumber(FCV_SEK);

			}

			//Call Component Macro
			//Call Component Macro: Cursor(9, 0)
			FCD_LCDDisplay0_Cursor(9, 0);

			//Call Component Macro
			//Call Component Macro: PrintString(":")
			FCD_LCDDisplay0_PrintString(":", 1);

			//Decision
			//Decision: sto < 10?
			if (FCV_STO < 10)
			{

				//Call Component Macro
				//Call Component Macro: Cursor(11, 0)
				FCD_LCDDisplay0_Cursor(11, 0);

				//Call Component Macro
				//Call Component Macro: PrintNumber(sto)
				FCD_LCDDisplay0_PrintNumber(FCV_STO);

				//Call Component Macro
				//Call Component Macro: Cursor(10, 0)
				FCD_LCDDisplay0_Cursor(10, 0);

				//Call Component Macro
				//Call Component Macro: PrintNumber(sto1)
				FCD_LCDDisplay0_PrintNumber(FCV_STO1);

			} else {

				//Call Component Macro
				//Call Component Macro: Cursor(10, 0)
				FCD_LCDDisplay0_Cursor(10, 0);

				//Call Component Macro
				//Call Component Macro: PrintNumber(sto)
				FCD_LCDDisplay0_PrintNumber(FCV_STO);

			}


		}

		//Loop
		//Loop: While st1 == 0 AND st2 == 0 AND st3 == 1
		while (FCV_ST1 == 0 & FCV_ST2 == 0 & FCV_ST3 == 1)
		{

			//Call Component Macro
			//Call Component Macro: start=ReadState()
			FCV_START = FCD_SWITCH0_ReadState();

			//Call Component Macro
			//Call Component Macro: stop=ReadState()
			FCV_STOP = FCD_SWITCH1_ReadState();

			//Decision
			//Decision: stop == 1?
			if (FCV_STOP == 1)
			{

				//Calculation
				//Calculation:
				//  st1 = 0
				//  st2 = 1
				//  st3 = 0
				FCV_ST1 = 0;
				FCV_ST2 = 1;
				FCV_ST3 = 0;

			// } else {

			}

			//Decision
			//Decision: start == 1?
			if (FCV_START == 1)
			{

				//Calculation
				//Calculation:
				//  st1 = 1
				//  st2 = 0
				//  st3 = 0
				FCV_ST1 = 1;
				FCV_ST2 = 0;
				FCV_ST3 = 0;

			// } else {

			}

			//Calculation
			//Calculation:
			//  sto = 0
			//  min = 0
			//  sek = 0
			FCV_STO = 0;
			FCV_MIN = 0;
			FCV_SEK = 0;

			//Decision
			//Decision: min < 10?
			if (FCV_MIN < 10)
			{

				//Call Component Macro
				//Call Component Macro: Cursor(5, 0)
				FCD_LCDDisplay0_Cursor(5, 0);

				//Call Component Macro
				//Call Component Macro: PrintNumber(min1)
				FCD_LCDDisplay0_PrintNumber(FCV_MIN1);

				//Call Component Macro
				//Call Component Macro: Cursor(4, 0)
				FCD_LCDDisplay0_Cursor(4, 0);

				//Call Component Macro
				//Call Component Macro: PrintNumber(min)
				FCD_LCDDisplay0_PrintNumber(FCV_MIN);

			} else {

				//Call Component Macro
				//Call Component Macro: Cursor(5, 0)
				FCD_LCDDisplay0_Cursor(5, 0);

				//Call Component Macro
				//Call Component Macro: PrintNumber(min)
				FCD_LCDDisplay0_PrintNumber(FCV_MIN);

			}

			//Call Component Macro
			//Call Component Macro: Cursor(6, 0)
			FCD_LCDDisplay0_Cursor(6, 0);

			//Call Component Macro
			//Call Component Macro: PrintString(":")
			FCD_LCDDisplay0_PrintString(":", 1);

			//Decision
			//Decision: sek < 10?
			if (FCV_SEK < 10)
			{

				//Call Component Macro
				//Call Component Macro: Cursor(8, 0)
				FCD_LCDDisplay0_Cursor(8, 0);

				//Call Component Macro
				//Call Component Macro: PrintNumber(sek)
				FCD_LCDDisplay0_PrintNumber(FCV_SEK);

				//Call Component Macro
				//Call Component Macro: Cursor(7, 0)
				FCD_LCDDisplay0_Cursor(7, 0);

				//Call Component Macro
				//Call Component Macro: PrintNumber(sek1)
				FCD_LCDDisplay0_PrintNumber(FCV_SEK1);

			} else {

				//Call Component Macro
				//Call Component Macro: Cursor(7, 0)
				FCD_LCDDisplay0_Cursor(7, 0);

				//Call Component Macro
				//Call Component Macro: PrintNumber(sek)
				FCD_LCDDisplay0_PrintNumber(FCV_SEK);

			}

			//Call Component Macro
			//Call Component Macro: Cursor(9, 0)
			FCD_LCDDisplay0_Cursor(9, 0);

			//Call Component Macro
			//Call Component Macro: PrintString(":")
			FCD_LCDDisplay0_PrintString(":", 1);

			//Decision
			//Decision: sto < 10?
			if (FCV_STO < 10)
			{

				//Call Component Macro
				//Call Component Macro: Cursor(11, 0)
				FCD_LCDDisplay0_Cursor(11, 0);

				//Call Component Macro
				//Call Component Macro: PrintNumber(sto)
				FCD_LCDDisplay0_PrintNumber(FCV_STO);

				//Call Component Macro
				//Call Component Macro: Cursor(10, 0)
				FCD_LCDDisplay0_Cursor(10, 0);

				//Call Component Macro
				//Call Component Macro: PrintNumber(sto1)
				FCD_LCDDisplay0_PrintNumber(FCV_STO1);

			} else {

				//Call Component Macro
				//Call Component Macro: Cursor(10, 0)
				FCD_LCDDisplay0_Cursor(10, 0);

				//Call Component Macro
				//Call Component Macro: PrintNumber(sto)
				FCD_LCDDisplay0_PrintNumber(FCV_STO);

			}


		}


	}

	mainendloop: goto mainendloop;
}

void MX_INTERRUPT_MACRO(void)
{
}



